// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVuJz60K-1dgpnX-by21PmVx6n6a-Ivc',
    appId: '1:814415931035:web:d9b72ade4813f40586c83e',
    messagingSenderId: '814415931035',
    projectId: 'loginsignup-612ec',
    authDomain: 'loginsignup-612ec.firebaseapp.com',
    storageBucket: 'loginsignup-612ec.appspot.com',
    measurementId: 'G-BVHVSH29JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHksnsv18ixC-o4dOorrdcTf0kGsMX7hk',
    appId: '1:814415931035:android:688cc0684fa1aeff86c83e',
    messagingSenderId: '814415931035',
    projectId: 'loginsignup-612ec',
    storageBucket: 'loginsignup-612ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAudt7HYZwmwaYnsUiJ4E24VLrVn54hkgY',
    appId: '1:814415931035:ios:481cca4cfd33c72f86c83e',
    messagingSenderId: '814415931035',
    projectId: 'loginsignup-612ec',
    storageBucket: 'loginsignup-612ec.appspot.com',
    iosClientId: '814415931035-pn1700dh809nkhjsh6me544g5hqrn789.apps.googleusercontent.com',
    iosBundleId: 'com.example.chms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAudt7HYZwmwaYnsUiJ4E24VLrVn54hkgY',
    appId: '1:814415931035:ios:9a9192c3957ebc6b86c83e',
    messagingSenderId: '814415931035',
    projectId: 'loginsignup-612ec',
    storageBucket: 'loginsignup-612ec.appspot.com',
    iosClientId: '814415931035-qfmpn25h5ct1i7pc89rjbf1p31it17l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chms.RunnerTests',
  );
}
